services:
  - type: web
    name: youtube_converter
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
    - key: SECRET_KEY
      generateValue: true
    - key: DEBUG
      value: "0"
    - key: ALLOWED_HOSTS
      value: "youtube-converter.onrender.com"